### PR TITLE
UX: Fixed Reaction animation for mobile

### PR DESCRIPTION
**Pull request by Ahmedgagan**

### CODE REVIEW

**Comment by Ahmedgagan** [comment]
@jjaffeux

**Comment by jjaffeux** [comment]
sorry I don't get from the title what it fixes

**Comment by Ahmedgagan** [comment]
> sorry I don't get from the title what it fixes

Reaction animation in mobile was slightly off, so added a fix.
Also, the above commits were for the fix you did yesterday and I was not knowing, so removed all other code and just kept fix for animation in mobile

**Comment by jjaffeux** [comment]
> > sorry I don't get from the title what it fixes
> 
> Reaction animation in mobile was slightly off, so added a fix.
> Also, the above commits were for the fix you did yesterday and I was not knowing, so removed all other code and just kept fix for animation in mobile

I mean you should update your commit  title

**Pull request merged**
