### PR TITLE
FIX: Ignored RecordNotUnique error

### PR DESCRIPTION
**Pull request by Ahmedgagan**
@jjaffeux

### CODE REVIEW

**Comment by Ahmedgagan** [comment]
@jjaffeux can you suggest to me how to write the spec for this? 
As it's not defined when will the backend raise this issue, I removed this recuse block and fired 20 requests together in a spec file but all requests were successful.
Also, I checked out in the core there's no spec for this type of ignoring rescue block.

Screenshot 2021-03-10 at 12 54 09 PM

**Comment by jjaffeux** [comment]
why is it closed ?

**Comment by Ahmedgagan** [comment]
> why is it closed ?

Sorry for the mess, there was some issue in managing the branch. I have added a new PR for this here
https://github.com/discourse/discourse-reactions/pull/38

**Comment by jjaffeux** [comment]
The way you write a spec for this:
- first you remove the code you added, this way you can ensure there was an issue before
- in  your spec I would image you attempt to create this record and yen call toggle, it should raise an error no?
- you can use `expect { # code }.to_not raise_error`

**Pull request closed without merging**
