### PR TITLE
FEATURE: Show users list on hover of reaction in reactions-panel

### PR DESCRIPTION
**Pull request by Ahmedgagan**
@jjaffeux 
- Display users list on hover
- display reaction-state-panel on click

### CODE REVIEW

**Comment by jjaffeux** [comment]
can you include a screenshot please ?

**Comment by Ahmedgagan** [comment]
> can you include a screenshot please ?



https://user-images.githubusercontent.com/35112518/109509112-919c8780-7ac6-11eb-8de1-92721613e3e6.mov

**Comment by jjaffeux** [comment]
It feels to slow when you hover from one to another, should be instant as much as possible

**Comment by Ahmedgagan** [comment]
@jjaffeux does this one look nice?

https://user-images.githubusercontent.com/35112518/109512218-dfff5580-7ac9-11eb-9ed6-8f68acb281cf.mov

**Comment by jjaffeux** [comment]
Much better

**Review by jjaffeux — APPROVED** [review]

**Pull request merged**
