### PR TITLE
DEV: Bind rake task to run only on development environment

### PR DESCRIPTION
**Pull request by Ahmedgagan**
@jjaffeux

### CODE REVIEW

**Review by jjaffeux — CHANGES_REQUESTED** [review]
hmmm that seems weird, feel like you are assigning value here and not checking value

**Comment by Ahmedgagan** [comment]
> hmmm that seems weird, feel like you are assigning value here and not checking value

That's true. added a fix for this

**Comment by jjaffeux** [comment]
Sorry I should have said it before but we should display some basic error message too.

**Comment by Ahmedgagan** [comment]
I have added the message in `raise` 😅 do we need any other message too?

**Comment by Ahmedgagan** [comment]
Screenshot 2021-03-11 at 1 59 10 AM

**Review by jjaffeux — APPROVED** [review]

**Pull request merged**
