### PR TITLE
DEV: Uses 'discourse_reactions_like_icon' setting to display emoji/icon for main-reaction

### PR DESCRIPTION
**Pull request by Ahmedgagan**
@jjaffeux 
Uses `discourse_reactions_like_icon` setting to display emoji/icon for main-reaction

### CODE REVIEW

**Comment by jjaffeux** [comment]
Can you explain more what it does please ?

"Fixes the use of settings 'discourse_reactions_like_icon' & 'discourse_reactions_reaction_for_like'"

this doesn’t tell anything

**Comment by Ahmedgagan** [comment]
Yesterday I tried to change the setting `discourse_reactions_reaction_for_like` many things were breaking.
eg: when `discourse_reactions_reaction_for_like=laughing` & `discourse_reactions_like_icon=heart`
In reactions picker, the icon for laughing reaction should show `heart` and in the reactions button also it should show `heart`
But instead of heart it was displaying `laughing` emoji in picker & `heart` in the reaction button.
Like this many small issues were there.

**Comment by jjaffeux** [comment]
Ok cool :+1:

Now please try to update your commit message with this explanation, slightly more formal if possible please.

**Comment by Ahmedgagan** [comment]
> Ok cool 👍
> 
> Now please try to update your commit message with this explanation, slightly more formal if possible please.

Added the new message, does it seems okay?

**Comment by jjaffeux** [comment]
better yes thanks

**Pull request merged**
